apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test-pod
  labels:
    provider: kubernetes
    guide: self
spec:
  compositeTypeRef:
    apiVersion: ahmed.mellina.tn/v1alpha1
    kind: rTestPod
  patchSets:
    - name: metadata
      patches:
        - fromFieldPath: metadata.labels
  resources:
    - name: testpod
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Pod
              metadata:
                name: crossplane-pod
                namespace: default
              spec:
                imagePullPolicy: ifNotPresent
          providerConfigRef:
            name: kubernetes-provider      
      patches:
        - fromFieldPath: "spec.containers[0].podImage"
          toFieldPath: "spec.forProvider.manifest.spec.containers[0].image"
        - fromFieldPath: "spec.containers[0].podName"
          toFieldPath: "spec.forProvider.manifest.spec.containers[0].name" 
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"